version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/python:3.9.5
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl and use pipenv to install dependencies
            python setup.py sdist bdist_wheel
            pip install pipenv
            pip install pytest
            pip install -r requirements.txt
            pipenv install dist/southpaw-0.0.9-py3-none-any.whl
            pipenv install pytest
            python -m pytest
            pip install pdoc3   
            mkdir /tmp/documentation
            pdoc3 -h
            pdoc3 --html ./ --output-dir /tmp/documentation
      - store_artifacts:
          path: /tmp/documentation

  test_pypi_publish:
    docker:
      - image: circleci/python:3.9.5
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish to Test PyPI
            python setup.py sdist bdist_wheel
            pip install pipenv
            pipenv install twine
            pipenv run twine upload --repository testpypi dist/*
  pypi_publish:
    docker:
      - image: circleci/python:3.9.5
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish to PyPI
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install twine
            pipenv run twine upload dist/*
workflows:
  build_test_publish:
    jobs:
      - build_test
      - test_pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - develop
      - pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - main
